install: 0

settings:
    default_vhost: 1
    proxy_buffers: 4 256k
    proxy_buffer_size: 128k

vhosts:
    -
        server_name: awesome.dev
        server_aliases:
            - www.awesome.dev
        www_root: /var/www/awesome
        proxy: ''
        listen_port: 80
        ssl: false
        ssl_port: 443
        ssl_cert: ''
        ssl_key: ''
        rewrite_to_https: 0
        spdy: 0
        envvars:
            - APP_ENV dev
        index_files:
            - index.html
            - index.htm
            - index.php
        location: '\.php$'
        location_prepend: []
        location_append: {}
        engine: php
        client_max_body_size: '1m'
