services:
    puphpet.extension.redis.configure:
        class: Puphpet\Extension\RedisBundle\Configure
        arguments:
            - @service_container

    puphpet.extension.redis.front_controller:
        class: Puphpet\Extension\RedisBundle\Controller\FrontController
        calls:
            - [ setContainer, [@service_container] ]
