parameters:

services:
    puphpet.extension.python.configure:
        class: Puphpet\Extension\PythonBundle\Configure
        arguments:
            - @service_container

    puphpet.extension.python.front_controller:
        class: Puphpet\Extension\PythonBundle\Controller\FrontController
        calls:
            - [ setContainer, [@service_container] ]
