parameters:

services:
    puphpet.extension.sqlite.configure:
        class: Puphpet\Extension\SqliteBundle\Configure
        arguments:
            - @service_container

    puphpet.extension.sqlite.front_controller:
        class: Puphpet\Extension\SqliteBundle\Controller\FrontController
        calls:
            - [ setContainer, [@service_container] ]
