parameters:

services:
    puphpet.extension.vagrantfile.softlayer.configure:
        class: Puphpet\Extension\VagrantfileSoftlayerBundle\Configure
        arguments:
            - @service_container

    puphpet.extension.vagrantfile.softlayer.front_controller:
        class: Puphpet\Extension\VagrantfileSoftlayerBundle\Controller\FrontController
        calls:
            - [ setContainer, [@service_container] ]

    puphpet.extension.vagrantfile.softlayer.manifest_controller:
        class: Puphpet\Extension\VagrantfileSoftlayerBundle\Controller\ManifestController
        calls:
            - [ setContainer, [@service_container] ]
