empty_vhost:
    servername: ~
    serveraliases: []
    docroot: ~
    port: 80
    setenv: []
    directories:
        -
            provider: directory
            path: 1
            options: []
            allow_override: []
            require: []
            custom_fragment: ~
    custom_fragment: ~
    ssl: 0
    ssl_cert: ~
    ssl_key: ~
    ssl_chain: ~
    ssl_certs_dir: ~
    engine: ~

available_modules:
    - cache
    - cgid
    - dav
    - dav_fs
    - deflate
    - disk_cache
    - expires
    - headers
    - info
    - ldap
    - mime_magic
    - proxy_ajp
    - proxy_balancer
    - proxy
    - rewrite
    - ssl
    - userdir
    - vhost_alias

available_engines:
    - none
    - php
