install: 1

settings:
    sendfile: 0

modules:
    - rewrite

vhosts:
    -
        servername: awesome.dev
        serveraliases:
            - www.awesome.dev
        docroot: /var/www/awesome
        port: 80
        setenv:
            - APP_ENV dev
        directories:
            -
                provider: directory
                path: /var/www/awesome
                options:
                    - Indexes
                    - FollowSymlinks
                    - MultiViews
                allow_override:
                    - All
                require:
                    - all
                    - granted
                custom_fragment: ''
        custom_fragment: ~
        ssl: 0
        ssl_cert: ~
        ssl_key: ~
        ssl_chain: ~
        ssl_certs_dir: ~
        engine: php

mod_pagespeed: 0
